# Generated by Django 5.2.9 on 2026-01-08 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('kakao_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('road_address', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('place_url', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenStatusLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('is_open_now', models.BooleanField(blank=True, null=True)),
                ('today_open_time', models.TextField(blank=True, null=True)),
                ('today_close_time', models.TextField(blank=True, null=True)),
                ('minutes_to_close', models.IntegerField(blank=True, null=True)),
                ('today_status_note', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='cafes.place')),
            ],
            options={
                'indexes': [models.Index(fields=['place', '-checked_at'], name='cafes_opens_place_i_18b3f8_idx'), models.Index(fields=['-checked_at'], name='cafes_opens_checked_7e9f4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaceDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('holiday_desc', models.TextField(blank=True, null=True)),
                ('opening_hours_text', models.TextField(blank=True, null=True)),
                ('opening_hours_json', models.TextField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cafes.place')),
            ],
            options={
                'indexes': [models.Index(fields=['place', '-fetched_at'], name='cafes_place_place_i_afcf80_idx')],
            },
        ),
    ]
