# Generated by Django 5.2.9 on 2026-01-09 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe24h',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('today_open_time', models.TextField(blank=True, null=True)),
                ('today_close_time', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cafe24h', to='cafes.place')),
            ],
            options={
                'db_table': 'cafes_cafe24h',
            },
        ),
    ]
