# Generated by Django 5.2.9 on 2026-01-21 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('cafes', '0002_cafe24h'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='cafes.place'),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='cafe_name',
        ),
    ]
